apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: laravel-php
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`localhost`) && PathPrefix(`/api/php`)
      middlewares:
        - name: strip-api-prefixes
          namespace: demo-app
      services:
        - kind: Service
          name: laravel-web-service 
          port: 80
          scheme: http
