apiVersion: v1
kind: Service
metadata:
  name: laravel-web-service
  namespace: demo-app
  labels:
    app: laravel-php
spec:
  selector:
    app: laravel-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
