apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vue-frontend
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`vue-test.com`)
      services:
        - kind: Service
          name: vue-frontend
          port: 8080
          scheme: http